services:
  iron_nest:
    image: ghcr.io/jiyuu-jin/ironnest:latest
    build: .
    network_mode: "host"
    init: true
    volumes:
      - "./docker-data/app/:/app/data/"
    restart: "unless-stopped"
    environment:
      LEPTOS_SITE_ADDR: "0.0.0.0:80"

  postgres:
    image: postgres:17
    ports:
      - "127.0.0.1:5433:5432"
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - "./docker-data/postgres:/var/lib/postgresql/data:rw"

#   traefik:
#     image: "traefik:v2.9"
#     restart: always
#     command:
#       - "--providers.docker=true"
#       - "--configFile=/etc/traefik/traefik.yml"
#       - "--entrypoints.websecure.address=:443"
#       - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
#       - "--certificatesresolvers.letsencrypt.acme.email=${TRAEFIK_ACME_EMAIL}"
#       - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
#     ports:
#       - "443:443"
#     volumes:
#       - "./data/letsencrypt:/letsencrypt"
#       - "/var/run/docker.sock:/var/run/docker.sock:ro"
