[package]
name = "mish-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.38", features = ["derive"] }
reqwest = { workspace = true, features = ["json"] }
serde_json = "1.0.140"
tokio = { workspace = true, features = ["full"] }
